# Generated by Django 2.1.3 on 2018-12-22 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='csefewf', max_length=4)),
                ('qqnum', models.CharField(default='1345215', max_length=12)),
                ('telnum', models.CharField(default='41414141', max_length=11)),
                ('mailnum', models.EmailField(default='dfdg@gmail.com', max_length=20)),
                ('address', models.CharField(default='defw4344rt', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.User')),
            ],
        ),
    ]
